"""add qr_codes table

Revision ID: 89a5ac96daca
Revises: 5f982bc10a2b
Create Date: 2026-05-31 10:09:21.943682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89a5ac96daca'
down_revision: Union[str, Sequence[str], None] = '5f982bc10a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_codes',
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('medecin_id', sa.Integer(), nullable=True),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('expire_le', sa.DateTime(), nullable=True),
    sa.Column('nombre_scans', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_modified_by', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_modified_on', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['medecin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_codes_id'), 'qr_codes', ['id'], unique=False)
    op.create_index(op.f('ix_qr_codes_token'), 'qr_codes', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qr_codes_token'), table_name='qr_codes')
    op.drop_index(op.f('ix_qr_codes_id'), table_name='qr_codes')
    op.drop_table('qr_codes')
    # ### end Alembic commands ###
