"""add sessions table

Revision ID: 8af183dc8e47
Revises: 89a5ac96daca
Create Date: 2026-06-02 16:46:57.004277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8af183dc8e47'
down_revision: Union[str, Sequence[str], None] = '89a5ac96daca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('date_jour1', sa.Date(), nullable=False),
    sa.Column('date_jour2', sa.Date(), nullable=True),
    sa.Column('date_jour3', sa.Date(), nullable=True),
    sa.Column('mesures_j1_matin', sa.Integer(), nullable=True),
    sa.Column('mesures_j1_soir', sa.Integer(), nullable=True),
    sa.Column('mesures_j2_matin', sa.Integer(), nullable=True),
    sa.Column('mesures_j2_soir', sa.Integer(), nullable=True),
    sa.Column('mesures_j3_matin', sa.Integer(), nullable=True),
    sa.Column('mesures_j3_soir', sa.Integer(), nullable=True),
    sa.Column('jour1_complete', sa.Boolean(), nullable=True),
    sa.Column('jour2_complete', sa.Boolean(), nullable=True),
    sa.Column('jour3_complete', sa.Boolean(), nullable=True),
    sa.Column('protocole_termine', sa.Boolean(), nullable=True),
    sa.Column('medicament_pris', sa.Boolean(), nullable=True),
    sa.Column('demarre_le', sa.DateTime(), nullable=False),
    sa.Column('termine_le', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_modified_by', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_modified_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_session_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
