"""add est_hypertendu to patients

Revision ID: e216088ae3db
Revises: 4bf43dd1819c
Create Date: 2026-06-06 16:07:06.601498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e216088ae3db'
down_revision: Union[str, Sequence[str], None] = '4bf43dd1819c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('est_hypertendu', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('patients', 'seuil_diastolique_eleve')
    op.drop_column('patients', 'seuil_systolique_eleve')
    op.drop_column('patients', 'seuil_diastolique_critique')
    op.drop_column('patients', 'seuil_diastolique_hypertension')
    op.drop_column('patients', 'seuil_systolique_critique')
    op.drop_column('patients', 'seuil_systolique_hypertension')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('seuil_systolique_hypertension', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('seuil_systolique_critique', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('seuil_diastolique_hypertension', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('seuil_diastolique_critique', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('seuil_systolique_eleve', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('seuil_diastolique_eleve', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('patients', 'est_hypertendu')
    # ### end Alembic commands ###
