"""add profil_complete to patients

Revision ID: e39e351d0f14
Revises: 730c23115628
Create Date: 2026-06-07 00:25:15.851066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e39e351d0f14'
down_revision: Union[str, Sequence[str], None] = '730c23115628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('profil_complete', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'profil_complete')
    # ### end Alembic commands ###
