"""initial migration

Revision ID: fabfe730599f
Revises: a42e64da8385
Create Date: 2026-05-05 11:23:50.498979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fabfe730599f'
down_revision: Union[str, Sequence[str], None] = 'a42e64da8385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('nif_structure', sa.String(length=50), nullable=True),
    sa.Column('raison_sociale', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_modified_by', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_modified_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_organisations_id'), 'organisations', ['id'], unique=False)
    op.add_column('alertes', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'alertes', 'organisations', ['organisation_id'], ['id'])
    op.add_column('audit_trails', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'audit_trails', 'organisations', ['organisation_id'], ['id'])
    op.add_column('mesures', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mesures', 'organisations', ['organisation_id'], ['id'])
    op.add_column('patients', sa.Column('medecin_id', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patients', 'users', ['medecin_id'], ['id'])
    op.create_foreign_key(None, 'patients', 'organisations', ['organisation_id'], ['id'])
    op.add_column('permissions', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'permissions', 'organisations', ['organisation_id'], ['id'])
    op.add_column('roles', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'roles', 'organisations', ['organisation_id'], ['id'])
    op.add_column('tokens', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tokens', 'organisations', ['organisation_id'], ['id'])
    op.add_column('users', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'organisations', ['organisation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organisation_id')
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.drop_column('tokens', 'organisation_id')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'organisation_id')
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_column('permissions', 'organisation_id')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'organisation_id')
    op.drop_column('patients', 'medecin_id')
    op.drop_constraint(None, 'mesures', type_='foreignkey')
    op.drop_column('mesures', 'organisation_id')
    op.drop_constraint(None, 'audit_trails', type_='foreignkey')
    op.drop_column('audit_trails', 'organisation_id')
    op.drop_constraint(None, 'alertes', type_='foreignkey')
    op.drop_column('alertes', 'organisation_id')
    op.drop_index(op.f('ix_organisations_id'), table_name='organisations')
    op.drop_table('organisations')
    # ### end Alembic commands ###
